Don’t try to update non-existent summary
Fixes the misleading error:

  TypeError: view() got an unexpected keyword argument 'dir_path'

Which was the result of making an AJAX request with empty URL that gets
interpreted as index page view() which is not prepared for AJAX requests
(and shouldn’t).