Req: pycodestyle v2.1.0 breaks flake8 v3.0.4
flake8 v3.0.4 fails with pycodestyle v2.1.0 with this error:

"pycodestyle" requested unknown parameters causing 'FileProcessor'
object has no attribute 'previous_unindented_logical_line'

See https://gitlab.com/pycqa/flake8/issues/246
Fixed in
https://gitlab.com/pycqa/flake8/commit/6595d3a08dedec4ff07683bf2c8f5aca2637fc5f