ldapauth: fix crash on entering wrong password
LDAP_ is wrong prefix for unused passwords as it triggers exception
for wrong passwords:
ValueError: Unknown password hashing algorithm 'LDAP_Xnmn9ZRne376RMcSQK6YrUfd2rqmjaZP'.
Did you specify it in the PASSWORD_HASHERS setting?